language: rust
sudo: false

matrix:
  include:
    - rust: 1.15.0 # oldest supported version
      script: cargo build
    - rust: 1.19.0 # first release with the --tests flag
      script: cargo test --tests
    - rust: 1.26.0 # first release on which our doc tests pass
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - cargo test --features nightly
        - cargo test --no-default-features
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --features nightly
        - cargo update -Z minimal-versions && cargo build
    - rust: nightly
      name: WebAssembly
      install: rustup target add wasm32-unknown-unknown
      script: cargo test --target wasm32-unknown-unknown --no-run

before_script:
  - set -o errexit

script:
  - cargo test
  - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test

notifications:
  email:
    on_success: never
