language: rust
sudo: false

matrix:
  include:
    - rust: 1.15.0
    - rust: stable
    - rust: beta
    - rust: nightly
      install: rustup target add wasm32-unknown-unknown
      script: cargo test --target wasm32-unknown-unknown --no-run
    - rust: nightly
      script:
        - cargo test
        - cargo test --features nightly
        - cargo test --no-default-features
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --features nightly
        - cargo update -Z minimal-versions && cargo build

before_script:
  - set -o errexit

script:
  - cargo test
  - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test

notifications:
  email:
    on_success: never
