language: rust
sudo: false

matrix:
  include:
    - rust: 1.15.0 # oldest supported version
      script:
        - cargo build
        - cargo build --no-default-features
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build --no-default-features
    - rust: 1.19.0 # first release with the --tests flag
      script:
        - cargo test --tests
        - cargo test --no-default-features --tests
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --tests
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --no-default-features --tests
    - rust: 1.26.0 # first release on which our doc tests pass
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - cargo test --no-default-features
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --no-default-features
        - cargo update -Z minimal-versions && cargo build
    - rust: nightly
      name: WebAssembly
      install: rustup target add wasm32-unknown-unknown
      script: cargo test --target wasm32-unknown-unknown --no-run

before_script:
  - set -o errexit

script:
  - cargo test
  - cargo test --no-default-features
  - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test
  - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --no-default-features

notifications:
  email:
    on_success: never
