[package]
name = "proc-macro2"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
doctest = false

[dependencies]
synom = "0.11"
unicode-xid = "0.0.4"

[features]
unstable = []
