[package]
name = "proc-macro2"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
doctest = false

[dependencies]
unicode-xid = "0.1"

[dev-dependencies]
compiletest_rs = "0.2"

[features]
unstable = []
